version: '2'

services:
  cassandra-1:
    image: cassandra:${CASSTAG}
    networks:
      - stargate
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=c4-${CASSTAG}-cluster
  cassandra-2:
    image: cassandra:${CASSTAG}
    networks:
      - stargate
    mem_limit: 2G
    depends_on:
      - cassandra-1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=cassandra-1
      - CASSANDRA_CLUSTER_NAME=c4-${CASSTAG}-cluster
  cassandra-3:
    image: cassandra:${CASSTAG}
    networks:
      - stargate
    mem_limit: 2G
    depends_on:
      - cassandra-2
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=cassandra-1
      - CASSANDRA_CLUSTER_NAME=c4-${CASSTAG}-cluster
  coordinator:
    image: stargateio/coordinator-4_0:${SGTAG}
    depends_on:
      - cassandra-1
    networks:
      - stargate
    ports:
      - "9042:9042"
      - "8081:8081"
      - "8084:8084"
      - "8090:8090"
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=c4-${CASSTAG}-cluster
      - CLUSTER_VERSION=4.0
      - SEED=cassandra-1
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=true
  kvstoreapi:
    image: stargate-cmu/key-value-store:latest
    depends_on:
      - coordinator
    networks:
      - stargate
    ports:
      - "8083:8083"
      - "8080:8085"
    mem_limit: 2G
    environment:
      - QUARKUS_GRPC_CLIENTS_BRIDGE_HOST=coordinator
      - QUARKUS_GRPC_CLIENTS_BRIDGE_PORT=8091
      - QUARKUS_HTTP_ACCESS_LOG_ENABLED=${REQUESTLOG}
      - QUARKUS_LOG_LEVEL=${LOGLEVEL}
networks:
  stargate:
